export const discos = [
    {
      id: 1,
      artista: "Camila Moreno",
      album: "Pangea",
      precio: 5400,
      stock: 5,
      img: "https://http2.mlstatic.com/D_NQ_NP_684137-MLC49052926068_022022-O.webp",
      desc:"El nuevo trabajo de Camila Moreno, Pangea vol. 1, cuenta con colaboraciones de Natalia Valdebenito, Natisú y Gepe. Además, se presenta por primera vez su versión de “Ojos Azules”, un clásico en su repertorio desde hace diez años.",
      video:"https://www.youtube.com/embed/Ze5wGNPOcpU",
      cat:"importado",
    },
    {
      id: 2,
      artista: "Luis Alberto Spinetta",
      album: "Artaud",
      precio: 4500,
      stock: 6,
      img: "https://http2.mlstatic.com/D_NQ_NP_613148-MLA49874171529_052022-W.webp",
      desc:"Artaud, publicado en Octubre de 1973, es oficialmente el tercer disco de Pescado Rabioso, pero técnicamente significa, en realidad, el segundo disco como solista de Luis Alberto Spinetta.",
      video:"https://www.youtube.com/embed/LXYZQTt-Kuo",
      cat:"nacional",
    },
    {
      id: 3,
      artista: "Rosario Bléfari",
      album: "Sector Apagado",
      precio: 6000,
      stock: 9,
      img: "https://http2.mlstatic.com/D_NQ_NP_873750-MLA49053979459_022022-O.webp",
      desc:"Rosario Bléfari, la marplatense ícono del indie nacional, encabeza el lanzamiento de este material de estudio solista que bautizó Sector apagado y que registró en voz, guitarra acústica y coros, acompañada por de Alejo Auslender en guitarra, Nicolás Merlino en bajo y Federico Orio en batería y percusión. El álbum fue grabado en Murillo Cine, durante abril y mayo de 2018, y mezclado por Ariel Schlichter. ",
      video:"https://www.youtube.com/embed/VuTVroHCF2g",
      cat:"nacional",
    },
    {
      id: 4,
      artista: "John Frusciante",
      album: "Pbx Funicular Intaglio Zone",
      precio: 11200,
      stock: 3,
      img: "https://http2.mlstatic.com/D_NQ_NP_784343-MLA29556568799_032019-O.webp",
      desc:"Frusciante flirtea con la electrónica sin perder la esencia de sus melodías en un disco sujeto al drum&bass, el sintetizador y la improvisación consentida.Con el EP de Letur-Lefr y ahora el LP de PBX Funicular Intaglio Zone llega la hora de evaluar a John Frusciante en su etapa fuera de los Red Hot Chili Peppers. Como explica en profundidad en su web oficial, el objetivo era hacer música electrónica y experimentar con ella como lleva queriendo hacer mucho tiempo. Los primeros temas del disco entran como un café solo con un fuerte sabor que a primeras puede incitar a tirar el disco por la ventana. ‘Intro/Sabam‘ calienta sintetizadores y guitarra, con ‘Hear Say‘ el café se hace más oscuro, y la experimentación y cambios repentinos de escala de ‘Bike‘ forman un sabor difícil de tolerar a primeras, pero con un Frusciante ya al máximo fuego de voz, un buen dominio de la edición electrónica y el juego de sonidos.  ",
      video:"https://www.youtube.com/embed/WYmUhGXCXQ0",
      cat:"importado",
    },
    {
      id: 5,
      artista: "Los Natas",
      album: "Ciudad De Brahman ",
      precio: 5200,
      stock: 7,
      img: "https://http2.mlstatic.com/D_NQ_NP_948422-MLA44568755952_012021-V.webp",
      desc:"Grabado durante un viaje a San Francisco, esta sesión de 1999 hace recordar a los días de Pink Floyd, King Crimson, Yes y Genesis. Atrayentes piezas musicales como «Brisa del Desierto», «Tufi Meme» y «Alohawaii» no se adhieren a una simple estructura de canción al estilo de estribillo/estrofa/estribillo; ni hacen que la banda pierda su objetivo progresista. Mientras que la banda puede sonar melódica como Pink Floyd o Genesis, su sonido tiende a ser mucho más pesado y más agresivo, debido a una creativa orientación al antiguo Heavy metal. Los Natas podrán amar la melodía y armonía, pero eso no evita que la banda proporcione algunos enérgicos y poderosos acordes cercanos al sonido de Black Sabbath o de Blue Cheer. Este impredecible álbum requiere de ser escuchado varias veces para ser absorbido musicalmente, pero para quienes no insisten en la simplicidad de la música, Ciudad de Brahman es altamente gratificante.",
      video:"https://www.youtube.com/embed/5vCkwLpzveY",
      cat:"importado",
    },
    {
      id: 6,
      artista: "Rosalia",
      album: "Motomami",
      precio: 1200,
      stock: 7,
      img: "https://http2.mlstatic.com/D_NQ_NP_944370-MLA51445587705_092022-O.webp",
      desc:"Motomami es el tercer álbum de estudio de la cantante española Rosalía, lanzado el 18 de marzo de 2022 y la versión deluxe denominada Motomami + lanzado el 9 de septiembre de 2022 a través de Columbia Records. Rosalía contó con el apoyo de los productores Noah Goldstein, Michael Uzowuru, Dylan Wiggins y Pharrell Williams, así como a su antiguo amigo El Guincho o el músico James Blake, para crear un álbum conceptual sobre sus sentimientos durante los últimos tres años en forma de un collage de las influencias musicales de la cantante, especialmente en la música latina; todo en un tono experimental.1​2​ Separado en dos partes, cuenta con la participación de The Weeknd y Tokischa, y se presenta como «el álbum más personal y confesional de Rosalía hasta el momento».",
      video:"https://www.youtube.com/embed/6o7bCAZSxsg",
      cat:"importado",
    },
    {
      id: 7,
      artista: "Sr Tomate",
      album: "Augurio",
      precio: 5400,
      stock: 2,
      img: "https://http2.mlstatic.com/D_NQ_NP_702055-MLA27460121783_052018-O.webp",
      desc:"Augurio supone un cambio sustancial para Sr. Tomate. Hasta ahora su obra se venía encastrando como un puzzle de pequeños testamentos folk-rock (canciones trágicas pero también celebratorias, ideales para musicalizar camas tristes o pogos en centros culturales), pero esta vez su propuesta se vuelve mucho más intrincada y compleja. Ahora la música de Tomate se descubre de a capas: sus canciones ya no dependen de la fuerza pregnante de la melodía, sino de la tensión entre los climas oscuros y una instrumentación abigarrada que se emparenta de perfil con el sonido global de la época.",
      video:"https://www.youtube.com/embed/btL9CQvWqmQ",
      cat:"nacional",
    },
    
  ];